# Generated by Django 3.2.6 on 2021-08-30 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title :')),
                ('title_ar', models.CharField(max_length=250, verbose_name='Title-ar :')),
                ('description', models.TextField(max_length=500, null=True, verbose_name='Description :')),
                ('description_ar', models.TextField(max_length=500, null=True, verbose_name='Description-ar :')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price :')),
                ('sale_price', models.IntegerField(blank=True, null=True, verbose_name='Sale Price :')),
                ('months', models.IntegerField(verbose_name='Months :')),
                ('not_1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Note 1 :')),
                ('not_2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Note 2 :')),
                ('not_3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Note 3 :')),
                ('not_4', models.CharField(blank=True, max_length=150, null=True, verbose_name='Note 4 :')),
                ('not_5', models.CharField(blank=True, max_length=150, null=True, verbose_name='Note 5 :')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
