# Generated by Django 3.2.6 on 2021-08-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='image', verbose_name='image :'),
            preserve_default=False,
        ),
    ]
